[package]
name = "news"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

derive = "1.0.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0"
colour = "0.6.0"
ureq = "2.4.0"